### ISSUE TITLE
Istio / Envoy returns 404 for invocations without a Host: header

### ISSUE THREAD

**Issue by BarDweller** [istio/old_issues_repo#170]
**Is this a BUG or FEATURE REQUEST?:** BUG
**Did you review istio.io/help and existing issues to identify if this is already solved or being worked on?**: Yes

**Bug:** Y

**What Version of Istio and Kubernetes are you using, where did you get Istio from, Installation details**
```
$> istioctl version 
Version: 0.4.0
GitRevision: 24089ea97c8d244493c93b499a666ddf4010b547
GitBranch: 6401744b90b43901b2aa4a8bced33c7bd54ffc13
User: root@cc5c34bbd1ee
GolangVersion: go1.9.1
$>kubectl version
lient Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.1", GitCommit:"3a1c9449a956b6026f075fa3134ff92f7d55f812", GitTreeState:"clean", BuildDate:"2018-01-04T11:52:23Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.3-7+154699da4767fd", GitCommit:"154699da4767fd4225cbaa91cc26abd71bc853c7", GitTreeState:"clean", BuildDate:"2017-08-28T06:41:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
Istio obtained via `curl -L https://git.io/getLatestIstio | sh -`
`istio.yaml` and `istio-initializer.yaml` applied to the cluster.

**Is Istio Auth enabled or not ?** No.

**What happened**: 

Made a request from one pod to another, using the ip address, and container port of the target port, via http. eg `http://10.1.57.1:9080/health`. Recieved 404 from envoy as response to request.

On further testing, if you include a `Host:` header in the request, with the service name as it's value, the request proceeds as expected.

**What you expected to happen:** 
Service at target address to be invoked, even without `Host:` header. 

The 404 is misleading, as the service IS up and running, and without Istio present on the cluster, can be invoked without a `Host:` header being required. This means Istio could break existing invocations if applied to a cluster. 

**How to reproduce it:** 

Deploy book info sample, exec into a pod, use curl or wget to hit the pod id & port of another bookinfo service (health endpoint is usually a good bet). 

**Feature Request:** N

**Describe the feature:** N/A

**Comment by Stono** [comment]
This might help you out btw https://github.com/istio/istio/issues/2833#issuecomment-360561220

**Comment by ldemailly** [comment]
envoy doesn't support http 1.0 and Host: is mandatory for http 1.1 and onward

**Comment by sapien99** [comment]
Hey guys, same problem here. I have several pods belonging to one deployment. I can call them by service/virtualservice without any problem using there servicename, but when i call them using their pod-ip (kubetcl get pods -o wide) i end up with a 404. When i set the servicename as the host-header i can reach it - but the pod with the ip i specified gets only called every second time (which is logical because the service name is specified and used as a routing criteria then).

is it possible to reach a certain pod by ip?
do i need a Virtualservice for doing that? How would it look like?

$istioctl version
Version: 1.0.1
GitRevision: 42773aacced474d97159902d20579a25b1f98106
User: root@832d5020b1d4
Hub: gcr.io/istio-release
GolangVersion: go1.10.1
BuildStatus: Clean

$kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:08:19Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ldemailly** [comment]
this repo isn't used anymore, can you please file an issue in istio/istio (you can link this one for context)

**Comment by sapien99** [comment]
Will do, thx
